name: crypto_mobile_app
description: A comprehensive crypto mobile application

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  rust_lib_crypto_mobile_app:
    path: rust_builder
  flutter_rust_bridge: 
    git:
      path: frb_dart
      url: https://github.com/Usernode-Labs/flutter_rust_bridge
      ref: 1a911e6435156487cb73929f652dd983ce3fabf6
  web3dart: ^2.7.3
  bip39: ^1.0.6
  bip32_bip44: ^1.0.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  collection: any
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/feature_flags.json
    - assets/images/
