---
name: crypto_mobile_app
description: A New Layer 1 Operated & Secured by users from their phones.
version: 0.2.8+16
publish_to: none
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.35.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: "^2.5.1"
  go_router: "^14.2.0"
  qr_flutter: "^4.1.0"
  rust_lib_crypto_mobile_app:
    path: rust_builder
  flutter_rust_bridge:
    git:
      url: https://github.com/Usernode-Labs/flutter_rust_bridge
      ref: 229548e05286634674c29df08ef457e534e52b2e
      path: frb_dart
  path_provider: "^2.1.4"
  shared_preferences: "^2.2.3"
  flutter_secure_storage: "^9.2.2"
  sentry_flutter: "^9.7.0"
  http: "^1.1.0"
  package_info_plus: "^9.0.0"
  device_info_plus: "^9.0.0"
  image_picker: "^1.0.0"
  freezed_annotation: "^2.4.4"
  logger: "^2.0.0"
  collection: any
  wakelock_plus: "^1.2.8"
  battery_plus: "^6.0.0"
  connectivity_plus: "^6.0.0"
  permission_handler: "^11.0.0"
  crypto: "^3.0.3"
  url_launcher: "^6.2.0"
  webview_flutter: "^4.10.0"
  widgetbook: "^3.10.0"
  flutter_markdown: "^0.7.6"
  material_symbols_icons: ^4.2906.0
  flutter_svg: ^2.2.3
dev_dependencies:
  flutter_lints: "^5.0.0"
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: "^2.5.2"
  build_runner: "^2.4.11"
  flutter_launcher_icons: "^0.14.4"
flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/feature_flags.json
  - assets/images/
  - lib/design_system/DESIGN_SYSTEM.md
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon-1024.png
