import 'package:flutter/material.dart';

/// "Color is Expensive" Material 3 theme — APCA-driven ink & paper philosophy.
///
/// Near-black primary (#18191B) as the attention locker. True achromatic
/// neutrals. Chromatic color reserved for semantic meaning.
///
/// Values sourced from `material-theme.json` generated via the APCA pipeline.
class ColorIsExpensiveTheme {
  final TextTheme textTheme;

  const ColorIsExpensiveTheme(this.textTheme);

  // ---------------------------------------------------------------------------
  // Light schemes
  // ---------------------------------------------------------------------------

  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF252627),
      surfaceTint: Color(0xFF252627),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFE2E2E4),
      onPrimaryContainer: Color(0xFF1B1B1C),
      secondary: Color(0xFF0055D9),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFD3D9FF),
      onSecondaryContainer: Color(0xFF003EBA),
      tertiary: Color(0xFF795A00),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFDE8C),
      onTertiaryContainer: Color(0xFF5F4200),
      error: Color(0xFFBD0F19),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFBFA9),
      onErrorContainer: Color(0xFF9C0003),
      surface: Color(0xFFFCFCFC),
      onSurface: Color(0xFF1B1B1B),
      onSurfaceVariant: Color(0xFF44474D),
      outline: Color(0xFF74777E),
      outlineVariant: Color(0xFFC4C6CC),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF303030),
      inversePrimary: Color(0xFFC5C6C8),
      primaryFixed: Color(0xFFE2E2E4),
      onPrimaryFixed: Color(0xFF1B1B1C),
      primaryFixedDim: Color(0xFFC5C6C8),
      onPrimaryFixedVariant: Color(0xFF464749),
      secondaryFixed: Color(0xFFD3D9FF),
      onSecondaryFixed: Color(0xFF141938),
      secondaryFixedDim: Color(0xFFAEBCFF),
      onSecondaryFixedVariant: Color(0xFF003EBA),
      tertiaryFixed: Color(0xFFFFDE8C),
      onTertiaryFixed: Color(0xFF251A00),
      tertiaryFixedDim: Color(0xFFEBC160),
      onTertiaryFixedVariant: Color(0xFF5F4200),
      surfaceDim: Color(0xFFDADADA),
      surfaceBright: Color(0xFFF9F9F9),
      surfaceContainerLowest: Color(0xFFFFFFFF),
      surfaceContainerLow: Color(0xFFF3F3F3),
      surfaceContainer: Color(0xFFEEEEEE),
      surfaceContainerHigh: Color(0xFFE8E8E8),
      surfaceContainerHighest: Color(0xFFE2E2E2),
    );
  }

  static ColorScheme lightMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF1B1B1C),
      surfaceTint: Color(0xFF252627),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFF252627),
      onPrimaryContainer: Color(0xFFFFFFFF),
      secondary: Color(0xFF003EBA),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFF486DED),
      onSecondaryContainer: Color(0xFFFFFFFF),
      tertiary: Color(0xFF5F4200),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFF957200),
      onTertiaryContainer: Color(0xFFFFFFFF),
      error: Color(0xFF9C0003),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFBD0F19),
      onErrorContainer: Color(0xFFFFFFFF),
      surface: Color(0xFFFCFCFC),
      onSurface: Color(0xFF111111),
      onSurfaceVariant: Color(0xFF393B41),
      outline: Color(0xFF5B5E65),
      outlineVariant: Color(0xFF8E9198),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF303030),
      inversePrimary: Color(0xFFC5C6C8),
      primaryFixed: Color(0xFF76777A),
      onPrimaryFixed: Color(0xFFFFFFFF),
      primaryFixedDim: Color(0xFF515255),
      onPrimaryFixedVariant: Color(0xFFFFFFFF),
      secondaryFixed: Color(0xFF486DED),
      onSecondaryFixed: Color(0xFFFFFFFF),
      secondaryFixedDim: Color(0xFF0049CB),
      onSecondaryFixedVariant: Color(0xFFFFFFFF),
      tertiaryFixed: Color(0xFF957200),
      onTertiaryFixed: Color(0xFFFFFFFF),
      tertiaryFixedDim: Color(0xFF6C4E00),
      onTertiaryFixedVariant: Color(0xFFFFFFFF),
      surfaceDim: Color(0xFFDADADA),
      surfaceBright: Color(0xFFF9F9F9),
      surfaceContainerLowest: Color(0xFFFFFFFF),
      surfaceContainerLow: Color(0xFFF1F1F1),
      surfaceContainer: Color(0xFFE2E2E2),
      surfaceContainerHigh: Color(0xFFD4D4D4),
      surfaceContainerHighest: Color(0xFFC6C6C6),
    );
  }

  static ColorScheme lightHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF111112),
      surfaceTint: Color(0xFF252627),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFF1B1B1C),
      onPrimaryContainer: Color(0xFFFFFFFF),
      secondary: Color(0xFF002A8F),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFF003EBA),
      onSecondaryContainer: Color(0xFFFFFFFF),
      tertiary: Color(0xFF452D00),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFF5F4200),
      onTertiaryContainer: Color(0xFFFFFFFF),
      error: Color(0xFF750000),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFF9C0003),
      onErrorContainer: Color(0xFFFFFFFF),
      surface: Color(0xFFFCFCFC),
      onSurface: Color(0xFF000000),
      onSurfaceVariant: Color(0xFF000000),
      outline: Color(0xFF2E3035),
      outlineVariant: Color(0xFF44474D),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFF303030),
      inversePrimary: Color(0xFFC5C6C8),
      primaryFixed: Color(0xFF1B1B1C),
      onPrimaryFixed: Color(0xFFFFFFFF),
      primaryFixedDim: Color(0xFF111112),
      onPrimaryFixedVariant: Color(0xFFFFFFFF),
      secondaryFixed: Color(0xFF003EBA),
      onSecondaryFixed: Color(0xFFFFFFFF),
      secondaryFixedDim: Color(0xFF002A8F),
      onSecondaryFixedVariant: Color(0xFFFFFFFF),
      tertiaryFixed: Color(0xFF5F4200),
      onTertiaryFixed: Color(0xFFFFFFFF),
      tertiaryFixedDim: Color(0xFF452D00),
      onTertiaryFixedVariant: Color(0xFFFFFFFF),
      surfaceDim: Color(0xFFD4D4D4),
      surfaceBright: Color(0xFFF9F9F9),
      surfaceContainerLowest: Color(0xFFFFFFFF),
      surfaceContainerLow: Color(0xFFF1F1F1),
      surfaceContainer: Color(0xFFE2E2E2),
      surfaceContainerHigh: Color(0xFFC6C6C6),
      surfaceContainerHighest: Color(0xFFB9B9B9),
    );
  }

  // ---------------------------------------------------------------------------
  // Dark schemes
  // ---------------------------------------------------------------------------

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFD4D4D6),
      surfaceTint: Color(0xFFC5C6C8),
      onPrimary: Color(0xFF252627),
      primaryContainer: Color(0xFF3A3B3D),
      onPrimaryContainer: Color(0xFFE2E2E4),
      secondary: Color(0xFFAEBCFF),
      onSecondary: Color(0xFF00227B),
      secondaryContainer: Color(0xFF003EBA),
      onSecondaryContainer: Color(0xFFD3D9FF),
      tertiary: Color(0xFFEBC160),
      onTertiary: Color(0xFF452D00),
      tertiaryContainer: Color(0xFF5F4200),
      onTertiaryContainer: Color(0xFFFFDE8C),
      error: Color(0xFFFFA28C),
      onError: Color(0xFF240D04),
      errorContainer: Color(0xFF9C0003),
      onErrorContainer: Color(0xFFFFBFA9),
      surface: Color(0xFF1B1B1B),
      onSurface: Color(0xFFEBEBEB),
      onSurfaceVariant: Color(0xFFC4C6CC),
      outline: Color(0xFF8E9198),
      outlineVariant: Color(0xFF5B5E65),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFE2E2E2),
      inversePrimary: Color(0xFF252627),
      primaryFixed: Color(0xFFE2E2E4),
      onPrimaryFixed: Color(0xFF1B1B1C),
      primaryFixedDim: Color(0xFFC5C6C8),
      onPrimaryFixedVariant: Color(0xFF3A3B3D),
      secondaryFixed: Color(0xFFD3D9FF),
      onSecondaryFixed: Color(0xFF141938),
      secondaryFixedDim: Color(0xFFAEBCFF),
      onSecondaryFixedVariant: Color(0xFF003EBA),
      tertiaryFixed: Color(0xFFFFDE8C),
      onTertiaryFixed: Color(0xFF251A00),
      tertiaryFixedDim: Color(0xFFEBC160),
      onTertiaryFixedVariant: Color(0xFF5F4200),
      surfaceDim: Color(0xFF1B1B1B),
      surfaceBright: Color(0xFF3B3B3B),
      surfaceContainerLowest: Color(0xFF111111),
      surfaceContainerLow: Color(0xFF262626),
      surfaceContainer: Color(0xFF262626),
      surfaceContainerHigh: Color(0xFF303030),
      surfaceContainerHighest: Color(0xFF3B3B3B),
    );
  }

  static ColorScheme darkMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFE2E2E4),
      surfaceTint: Color(0xFFC5C6C8),
      onPrimary: Color(0xFF1B1B1C),
      primaryContainer: Color(0xFF8F9193),
      onPrimaryContainer: Color(0xFFFFFFFF),
      secondary: Color(0xFFD3D9FF),
      onSecondary: Color(0xFF002076),
      secondaryContainer: Color(0xFF6286FF),
      onSecondaryContainer: Color(0xFFFFFFFF),
      tertiary: Color(0xFFFFDE8C),
      onTertiary: Color(0xFF3A2200),
      tertiaryContainer: Color(0xFFB38B0D),
      onTertiaryContainer: Color(0xFFFFFFFF),
      error: Color(0xFFFFBFA9),
      onError: Color(0xFF600000),
      errorContainer: Color(0xFFFE5646),
      onErrorContainer: Color(0xFFFFFFFF),
      surface: Color(0xFF1B1B1B),
      onSurface: Color(0xFFFFFFFF),
      onSurfaceVariant: Color(0xFFE1E2E7),
      outline: Color(0xFFA8ABB2),
      outlineVariant: Color(0xFF8E9198),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFE2E2E2),
      inversePrimary: Color(0xFF252627),
      primaryFixed: Color(0xFFE2E2E4),
      onPrimaryFixed: Color(0xFF111112),
      primaryFixedDim: Color(0xFFC5C6C8),
      onPrimaryFixedVariant: Color(0xFF303032),
      secondaryFixed: Color(0xFFD3D9FF),
      onSecondaryFixed: Color(0xFF100F1F),
      secondaryFixedDim: Color(0xFFAEBCFF),
      onSecondaryFixedVariant: Color(0xFF002A8F),
      tertiaryFixed: Color(0xFFFFDE8C),
      onTertiaryFixed: Color(0xFF181000),
      tertiaryFixedDim: Color(0xFFEBC160),
      onTertiaryFixedVariant: Color(0xFF452D00),
      surfaceDim: Color(0xFF1B1B1B),
      surfaceBright: Color(0xFF474747),
      surfaceContainerLowest: Color(0xFF000000),
      surfaceContainerLow: Color(0xFF1B1B1B),
      surfaceContainer: Color(0xFF262626),
      surfaceContainerHigh: Color(0xFF303030),
      surfaceContainerHighest: Color(0xFF3B3B3B),
    );
  }

  static ColorScheme darkHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFF0F1F1),
      surfaceTint: Color(0xFFC5C6C8),
      onPrimary: Color(0xFF000000),
      primaryContainer: Color(0xFFD4D4D6),
      onPrimaryContainer: Color(0xFF111112),
      secondary: Color(0xFFEEEDFF),
      onSecondary: Color(0xFF000000),
      secondaryContainer: Color(0xFFAEBCFF),
      onSecondaryContainer: Color(0xFF100F1F),
      tertiary: Color(0xFFFFEFCF),
      onTertiary: Color(0xFF000000),
      tertiaryContainer: Color(0xFFEBC160),
      onTertiaryContainer: Color(0xFF181000),
      error: Color(0xFFFFE4DA),
      onError: Color(0xFF000000),
      errorContainer: Color(0xFFFF9A83),
      onErrorContainer: Color(0xFF210B03),
      surface: Color(0xFF1B1B1B),
      onSurface: Color(0xFFFFFFFF),
      onSurfaceVariant: Color(0xFFFFFFFF),
      outline: Color(0xFFE1E2E7),
      outlineVariant: Color(0xFFC4C6CC),
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
      inverseSurface: Color(0xFFE2E2E2),
      inversePrimary: Color(0xFF252627),
      primaryFixed: Color(0xFFE2E2E4),
      onPrimaryFixed: Color(0xFF000000),
      primaryFixedDim: Color(0xFFC5C6C8),
      onPrimaryFixedVariant: Color(0xFF1B1B1C),
      secondaryFixed: Color(0xFFD3D9FF),
      onSecondaryFixed: Color(0xFF000000),
      secondaryFixedDim: Color(0xFFAEBCFF),
      onSecondaryFixedVariant: Color(0xFF141938),
      tertiaryFixed: Color(0xFFFFDE8C),
      onTertiaryFixed: Color(0xFF000000),
      tertiaryFixedDim: Color(0xFFEBC160),
      onTertiaryFixedVariant: Color(0xFF251A00),
      surfaceDim: Color(0xFF1B1B1B),
      surfaceBright: Color(0xFF525252),
      surfaceContainerLowest: Color(0xFF000000),
      surfaceContainerLow: Color(0xFF1B1B1B),
      surfaceContainer: Color(0xFF303030),
      surfaceContainerHigh: Color(0xFF3B3B3B),
      surfaceContainerHighest: Color(0xFF474747),
    );
  }

  // ---------------------------------------------------------------------------
  // ThemeData builders
  // ---------------------------------------------------------------------------

  ThemeData theme(ColorScheme colorScheme) => ThemeData(
        useMaterial3: true,
        brightness: colorScheme.brightness,
        colorScheme: colorScheme,
        textTheme: textTheme.apply(
          bodyColor: colorScheme.onSurface,
          displayColor: colorScheme.onSurface,
        ),
        scaffoldBackgroundColor: colorScheme.surface,
        canvasColor: colorScheme.surface,
      );

  ThemeData light() => theme(lightScheme());
  ThemeData lightMediumContrast() => theme(lightMediumContrastScheme());
  ThemeData lightHighContrast() => theme(lightHighContrastScheme());
  ThemeData dark() => theme(darkScheme());
  ThemeData darkMediumContrast() => theme(darkMediumContrastScheme());
  ThemeData darkHighContrast() => theme(darkHighContrastScheme());
}
